defaults:
  - _self_
  - launcher: local
  - data: pusht
  - model: lewm

output_model_name: lewm
subdir: ${hydra:job.id}

num_workers: 6
train_split: 0.9
seed: 3072
img_size: 224
embed_dim: 192
history_size: 3
scheduler_max_epochs: 100
scheduler_type: LinearWarmupCosineAnnealingLR
scheduler_interval: epoch
epoch_interval: 1

trainer:
  max_epochs: 100
  devices: auto
  accelerator: gpu
  precision: bf16
  gradient_clip_val: 1.0
  limit_train_batches: null
  limit_val_batches: null
  log_every_n_steps: null

loader:
  batch_size: 128
  num_workers: ${num_workers}
  persistent_workers: True
  prefetch_factor: 3
  pin_memory: True

optimizer:
  type: AdamW
  lr: 5e-5
  weight_decay: 1e-3

num_preds: 1

loss:
  sigreg:
    weight: 0.09
    kwargs:
      knots: 17
      num_proj: 1024
