_target_: jepa.JEPA

encoder:
  _target_: stable_pretraining.backbone.utils.vit_hf
  size: tiny
  patch_size: 14
  image_size: ${img_size}
  pretrained: false
  use_mask_token: false

predictor:
  _target_: module.ARPredictor
  num_frames: ${history_size}
  input_dim: ${embed_dim}
  hidden_dim: ${embed_dim}
  output_dim: ${embed_dim}
  depth: 6
  heads: 16
  mlp_dim: 2048
  dim_head: 64
  dropout: 0.1
  emb_dropout: 0.0
  dual_layernorm_adaln_implementation: eager
  dual_layernorm_adaln_kernel_repo_id: ${kernels.predictor_dual_layernorm_adaln.repo_id}

action_encoder:
  _target_: module.Embedder
  input_dim: ???
  emb_dim: ${embed_dim}

projector:
  _target_: module.MLP
  input_dim: ${embed_dim}
  output_dim: ${embed_dim}
  hidden_dim: 2048
  norm_fn:
    _target_: torch.nn.BatchNorm1d
    _partial_: true

pred_proj:
  _target_: module.MLP
  input_dim: ${embed_dim}
  output_dim: ${embed_dim}
  hidden_dim: 2048
  norm_fn:
    _target_: torch.nn.BatchNorm1d
    _partial_: true
